"""user_ticket

Revision ID: 0301a17bc42a
Revises: 4497d72fe2fc
Create Date: 2023-09-25 15:21:31.558175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0301a17bc42a'
down_revision = '4497d72fe2fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_tickets_novice_id_novices', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_tickets_sender_id_users'), 'users', ['sender_id'], ['id'])
        batch_op.drop_column('novice_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('novice_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_tickets_sender_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_tickets_novice_id_novices', 'novices', ['novice_id'], ['id'])
        batch_op.drop_column('sender_id')

    # ### end Alembic commands ###
