"""empty message

Revision ID: 0ae6d8ec7926
Revises: 49126cdb43d7
Create Date: 2023-09-12 10:17:59.108368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ae6d8ec7926'
down_revision = '49126cdb43d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('section')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section', sa.VARCHAR(length=64), nullable=True))

    # ### end Alembic commands ###
