"""'second_migration'

Revision ID: 3a57f3b924e0
Revises: 
Create Date: 2023-05-24 08:59:02.493079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a57f3b924e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('novices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nov_id', sa.Integer(), nullable=False))
        batch_op.drop_column('id')

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tickets_novice_id_novices', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_tickets_novice_id_novices'), 'novices', ['novice_id'], ['nov_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tickets_novice_id_novices'), type_='foreignkey')
        batch_op.create_foreign_key('fk_tickets_novice_id_novices', 'novices', ['novice_id'], ['id'])

    with op.batch_alter_table('novices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.drop_column('nov_id')

    # ### end Alembic commands ###
