"""'ticket_owner_session_id'

Revision ID: 50f817ace4fa
Revises: 93310be1d251
Create Date: 2023-06-13 09:28:19.453847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50f817ace4fa'
down_revision = '93310be1d251'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_viewer_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('team_viewer_id')

    # ### end Alembic commands ###
