"""user_novice_association

Revision ID: 610411b49128
Revises: fbf5b026e26b
Create Date: 2023-09-20 14:59:31.232391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '610411b49128'
down_revision = 'fbf5b026e26b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('novices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('close_ticket', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('novice_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('uq_novices_novice_username', type_='unique')
        batch_op.create_foreign_key(batch_op.f('fk_novices_novice_id_users'), 'users', ['novice_id'], ['id'])
        batch_op.drop_column('novice_username')
        batch_op.drop_column('updated_on')
        batch_op.drop_column('novice_name')
        batch_op.drop_column('novice_department')
        batch_op.drop_column('created_on')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('novices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_on', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('novice_department', sa.VARCHAR(length=32), nullable=False))
        batch_op.add_column(sa.Column('novice_name', sa.VARCHAR(length=128), nullable=False))
        batch_op.add_column(sa.Column('updated_on', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('novice_username', sa.VARCHAR(length=64), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_novices_novice_id_users'), type_='foreignkey')
        batch_op.create_unique_constraint('uq_novices_novice_username', ['novice_username'])
        batch_op.drop_column('novice_id')
        batch_op.drop_column('close_ticket')

    # ### end Alembic commands ###
