"""'novice_mod'

Revision ID: 64f906d70c3d
Revises: 3a57f3b924e0
Create Date: 2023-05-24 09:27:02.082810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64f906d70c3d'
down_revision = '3a57f3b924e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('novices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.drop_column('nov_id')

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.alter_column('novice_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('fk_tickets_novice_id_novices', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_tickets_novice_id_novices'), 'novices', ['novice_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tickets_novice_id_novices'), type_='foreignkey')
        batch_op.create_foreign_key('fk_tickets_novice_id_novices', 'novices', ['novice_id'], ['nov_id'])
        batch_op.alter_column('novice_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('novices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nov_id', sa.INTEGER(), nullable=False))
        batch_op.drop_column('id')

    # ### end Alembic commands ###
