"""role_based_access_control

Revision ID: 89f7c3d8a74c
Revises: 610411b49128
Create Date: 2023-09-25 09:08:44.592344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89f7c3d8a74c'
down_revision = '610411b49128'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('novices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_novices_novice_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_novices_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('novice_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_users_role_id_roles'), 'roles', ['role_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_role_id_roles'), type_='foreignkey')
        batch_op.drop_column('role_id')

    with op.batch_alter_table('novices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('novice_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_novices_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_novices_novice_id_users', 'users', ['novice_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
