"""'ticket_session_id'

Revision ID: f8e50061dd62
Revises: 64f906d70c3d
Create Date: 2023-06-13 09:13:52.787638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8e50061dd62'
down_revision = '64f906d70c3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_viewer_id', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('team_viewer_id')

    # ### end Alembic commands ###
